### ISSUE TITLE
gradle sync error on 3.0 canary 5 

### ISSUE THREAD

**Issue by holoduke** [googlesamples/android-instant-apps#18]
whenever i try to sync one of the example projects i am getting the following error:

Error:Android Gradle plugin 3.0.0-alpha5 must not be applied to project ...../AndroidStudioProjects/android-instant-apps/multi-feature-module/base since version 3.0.0-alpha5 was already applied to this project

<img width="1338" alt="screen shot 2017-07-04 at 11 11 57" src="https://user-images.githubusercontent.com/951209/27826247-4b396180-60aa-11e7-91d5-9ab08d12f752.png">

Is there any work around?

**Comment by xinyangmaojian** [comment]
i have this problem too .

**Comment by amartinz** [comment]
Disable "configure on demand" in settings and gradle.properties.

![image](https://user-images.githubusercontent.com/2779871/27970525-80683a0a-634f-11e7-9e74-198f0d2bcae9.png)

gradle.properties in your top project root
```
org.gradle.configureondemand=false
```

then stop all gradle daemons and go to "File -> Invalidate Caches / Restart" and invalidate and restart.

should be fixed in Canary 6

https://issuetracker.google.com/issues/63178989

**Comment by keyboardsurfer** [comment]
There is an update to alpha6 available in the repository now.
Please check if your issues persist and re-open the issue in that case.
