### ISSUE TITLE
cannot switch to debug variant

### ISSUE THREAD

**Issue by CodeMasterYi** [googlesamples/android-instant-apps#34]
i'd like to change the both modules to debug variant, but i encount an issue~~~
![issue10098](https://user-images.githubusercontent.com/10430162/32135886-bd9dd834-bc38-11e7-8893-d8b7eba16381.png)
as the pic above, i can not switch the module named GluttonyGame to debug variant even though i select 'debug' option showed in the pic thousands of times(PS: ide refuse to change to debug, refuse my request)~~~but i can switch the module libcocos2d to debug variant, then it shows this:
![issue10099](https://user-images.githubusercontent.com/10430162/32135943-89ccd644-bc39-11e7-9833-6499d02c8008.png)
i don't know what is happening!!!

Android Studio 3.0
Build #AI-171.4408382, built on October 21, 2017
JRE: 1.8.0_152-release-915-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by keyboardsurfer** [comment]
Hi and thanks for reporting this issue.
I do not see how this is related to the samples in this repository.
This seems to be an issue with a specific implementation of your project.
Please let me know if the issue also occurs with the `flavors` sample.

Otherwise I recommend filing a bug against [Android Studio](https://developer.android.com/studio/report-bugs.html).

**Comment by keyboardsurfer** [comment]
I recommend posting relevant sections of your build.gradle file combined with the description you gave here on [StackOverflow](https://stackoverflow.com/questions/tagged/android-instant-apps).
