### ISSUE TITLE
IsInstantApp is always false

### ISSUE THREAD

**Issue by grosalex** [googlesamples/android-instant-apps#51]
Hi, 
InstantApps.isInstantApp(this) always return false even when running instant app. Do you have any idea why?

Regards,

**Comment by brianchu** [comment]
How do you run it? I run instant app using 
`adb install-multiple -r -t --instantapp` and isInstantApp() returns ok.
You can also use **ia** command.

**Comment by miguelmontemayor** [comment]
How are you deploying the instant app? You may be deploying the installed app, which is why it's always returning false. You can verify you're launching the instant app by the lighting bolt in the corner of the launcher app icon.

There's instructions on how to locally deploy the instant experience from the instant-enabled app bundles in this [documentation](https://developer.android.com/topic/google-play-instant/getting-started/instant-enabled-app-bundle).

Closing this issue as stale, but feel free to reopen and follow up.
